# Generated by Django 3.2.6 on 2021-08-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_empleado_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='gender',
        ),
    ]
